# Generated by Django 5.0.3 on 2024-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mame", models.CharField(max_length=200)),
                ("catagory", models.CharField(max_length=180)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("description", models.TextField()),
                ("stars", models.IntegerField()),
            ],
        ),
    ]
